### ISSUE TITLE
Migration steps don't like methods with hyphens in the name

### ISSUE THREAD

**Issue by kblief** [binlecode/mongogee#16]
grails.plugin.mongogee.exception.MongogeeException: Mongogee data migration failed: Illegal class name "com/example/Mongogee001Service$_some_ad-hoc_method_name_closure4$doCall" in class file com/example/Mongogee001Service$_some_ad-hoc_method_name_closure4$doCall

**Comment by binlecode** [comment]
fixed and verified in dev-g3.2 branch.
